### ISSUE TITLE
[Question] Automatic signin

### ISSUE THREAD

**Issue by christopheSeeka** [waves-exchange/provider-web#34]
Some users are asking me if we have an option to keep account logged in on refresh with automatic signin autorisation for a certain time like what we have in Waves Keeper. Would this be something possible to integrate too ?

**Comment by tsigel** [comment]
Hello! We can't add automatic sign, because its not secure.

**Comment by christopheSeeka** [comment]
Ok thank you for the feedback, i'll inform my community.
