### ISSUE TITLE
Direct link to seed on provider

### ISSUE THREAD

**Issue by christopheSeeka** [waves-exchange/provider-web#51]
Hello,

i have several users complaining that they lost their account after clearing cache of browser.
I put a warning on my webapp to go get their seed on waves.exchange after creating new accounts but i think a direct link to a page on waves.exchange where they get the seed, from within signer after new account creation would really help avoid this problem. Would something like that be possible in future updates?

Thanks you.

**Comment by tsigel** [comment]
Hello!

Yes, in the next updates we will add a user interface to create a backup source phrase in the provider, but not soon.
